name: natulang_app
description: Voice-Based Language Learning App
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  record: ^5.0.0
  just_audio: ^0.9.36
  provider: ^6.0.5
  json_annotation: ^4.9.0
  path_provider: ^2.1.0
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
